server:
  port: 80

mongodb_db: oidcng
oidc_saml_mapping_path: classpath:/oidc/saml_mapping.json
openid_configuration_path: classpath:/openid-configuration-docker.json
secret_key_set_path: classpath:/secret_keyset.json
associated_data: 4CEFFA8B-90DD-4737-8B04-6DA51C5B29AE
access_token_one_way_hash_salt: secret
private_key_path: file:///config/saml.key
certificate_path: file:///config/saml.crt
default_acr_value: http://dev.openconext.local/assurance/loa1
secure_cookie: false
oidc_token_endpoint: https://connect.dev.openconext.local/oidc/token
environment: SURFconext DEV

features:
  # Do we enforce that the RS - if eduID pseudonymisation is required - belongs to the SURF IdP linked to the eduID user account?
  # We link RS's and SURF IdP's using the coin:institution-guid
  enforce-eduid-resource-server-linked-account: true
  # Do we show consent if configured for a RP in manage
  consent-enabled: true

sp:
  entity_id: https://connect.dev.openconext.local
  acs_location: https://connect.dev.openconext.local/login/saml2/sso/oidcng

idp:
  entity_id: https://engine.dev.openconext.local/authentication/idp/metadata
  sso_location: https://engine.dev.openconext.local/authentication/idp/single-sign-on
  saml_assertion_signing_key: classpath:/engine.dev.openconext.local.default.pem

spring:
  data:
    mongodb:
      uri: mongodb://oidcngrw:secret@mongo:27017/oidcng?ssl=false
  thymeleaf:
    cache: false
  main:
    banner-mode: off

manage:
  user: manage
  password: secret

token-api:
  # Is the token API enabled for Profile and eduID? If not access to the token API endpoints is forbidden
  enabled: true
  users:
    - user: eduid
      password: secret
    - user: profile
      password: secret

eduid:
  user: oidcng
  password: secret
  uri: https://eduid.dev.openconext.local/myconext/api/attribute-manipulation
  enabled: true
